#server:
#    port: 9000
#
#spring:
#    application:
#        name: order-service
#
#    zipkin:
#        base-url: http://127.0.0.1:9411/ #zipkin地址
#        discovery-client-enabled: false  #不用开启服务发现
#
#    sleuth:
#        sampler:
#            probability: 1.0 #采样百分比
#
#    cloud:
#        nacos:
#            discovery:
#                server-addr: 127.0.0.1:8848
